# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ebfb1840c293217c10645f720458b49757b2698af57c9970594a3c7749c7d319ec93aec31b0cb2becd4566fa467a49412bd3784c18af980f4b3b05e8ef52d18

test:
  secret_key_base: d6fce65631b5687f66e3691293cc2687b4a15fe7f81478d988babea7aa57ac8e6904ec63990d72dcd75e1fc0fee46f96abb6e17eb8964939a4861abb912e8ce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
